### ISSUE TITLE
add an example that demonstrates how to list posts

### ISSUE THREAD

**Issue by tmcw** [segmentio/metalsmith#108]
It doesn't look like any of the stock examples show how to create an 'index page' from which other pages are listed and linked.

**Comment by stefanhenze** [comment]
Second that. All examples deliberately omit linking between pages. I had to search quite a while to find an example to generate links from collections (found one here http://stackoverflow.com/questions/26694052/how-do-i-use-metalsmith-permalinks-in-a-handlebars-template) but I'm still trying to find out how to link to a specific page (e.g. to the about page) without typing the URL that may or may not be generated differently by the permalink plugin.

**Comment by sperand-io** [comment]
hey - great idea! I'll see how we could flesh this out a bit in the docs. the beauty of metalsmith is it lets you do whatever you want to the global metadata *or* to each file's metadata with plugins.

this can be taken care of with the [`metalsmith-collections`](http://github.com/segmentio/metalsmith-collections) plugin, which adds the files themselves to the global metadata in sorted sub-sections.

if you only have one kind of post, you can tag each post you want on the homepage as an "article".  ie with `collection: articles` in each post's yml

Since you're using the permalinks, plugin, put an `index.html` file in the top level of your `src` directory (which will have folders for each post). You needn't give it any contents, just reference a custom "index" template:

```yaml
---
template: index.html
---
```

then in your templates directory the index.html template might look like this (if you were using swig):

```swig
{% extends "layout.html" %}
{% block body %}
  <ul class="blog-post-list">
    {% for article in articles %}
      <li class="blog-post-list-item">
      <div>
          <h1>{{ article.title }}</h1>
            <p>By {{ article.author }}</p>
            <time>{{ article.date|date('F Y') }}</time>
          </div>
        <p>{{ article.excerpt | striptags }}</p>
      </div>
     </li>
    {% endfor %}
  </ul>
{% endblock %}
```

(assuming you were also using the [`metalsmith-excerpts`](https://github.com/segmentio/metalsmith-excerpts/blob/master/lib/index.js#L30)  plugin as well :)

... lmk if that makes any sense! leaving open so that we can add an example that accomplishes something similar

**Comment by tmcw** [comment]
Okay, so this needs two things:

* plugins need clearer documentation

and

* metalsmith needs to explain plugins better

Put another way,

![2015-01-14 at 10 23 am](https://cloud.githubusercontent.com/assets/32314/5741172/a33c5a9e-9bd7-11e4-8806-b741ec10a696.png)

Make this explicit rather than implied.

**Comment by sperand-io** [comment]
>Since everything is a plugin, the core library is actually just an abstraction for manipulating a directory of files.

https://github.com/segmentio/metalsmith#how-does-it-work

**Comment by ianstormtaylor** [comment]
Closing since it seems like an issue that could be solved by someone pull requesting the language that helps them understand it.
