### ISSUE TITLE
Invoke API extremely slower than metalsmith CLI

### ISSUE THREAD

**Issue by arielyang** [segmentio/metalsmith#116]
metalsmith CLI took about 1-2 sec. and invoke API about 9-10 sec.

metalsmith.json

{
  "source": "contents",
  "destination": "build",
  "plugins": {
    "metalsmith-assets": {
      "source": "assets",
      "destination": "assets"
    },
    "metalsmith-markdown": {},
    "metalsmith-templates": {
      "engine": "jade",
      "directory": "templates",
      "pretty": true
    }
  }
}

metalsmith.coffee

Metalsmith = require 'metalsmith'
assets = require 'metalsmith-assets'
markdown = require 'metalsmith-markdown'
templates = require 'metalsmith-templates'

Metalsmith(__dirname)
    .source('contents')
    .use(assets({
            source: 'assets'
            destination: 'assets'
        }))
    .use(markdown())
    .use(templates({
            engine: 'jade'
            directory: 'templates'
            pretty: true
        }))
    .build((err) ->
            if err
                console.log err
        )

**Comment by ianstormtaylor** [comment]
Hey, I'm not going to be able to debug this myself, but if you figure out why the slowdown happens or if it's really related to Metalsmith then I'd be happy to discuss a fix. Thanks!

**Comment by arielyang** [comment]
The function and implements of the codes above is completely same right? the metalsmith CLI is an encapsulation of the API.

**Comment by dominicbarnes** [comment]
I'm not seeing any slowdown in the JS API, and the CLI is just a thin wrapper for it. (as you pointed out) A test-case that demonstrates the problem you are describing would be _extremely_ useful, as I can't seem to reproduce on my own.

My suspicion is that something else may be interfering with performance. Since you're using coffeescript, is the transpilation step what could be slowing things down?

**Comment by arielyang** [comment]
No, javascript is the same. I'll try to repo a simple test-case later. THX.
