### ISSUE TITLE
Make files easier to traverse/query/filter/etc

### ISSUE THREAD

**Issue by dominicbarnes** [segmentio/metalsmith#118]
Lots of plugins seem to implement the same type of logic over and over again: (I know I've done it on several occasions alone)

 * looping
 * filtering
 * sorting
 * grouping
 * etc...

Right now, the way plugins are forced to operate is with more verbosity than I think should be necessary:

```js
Object.keys(files).forEach(function (key) {
  var file = files[key];
  // ...
});
```

Granted, it's not _hard_ to do stuff like this, but it certainly obfuscates the original intent of the code somewhat.

Thus, I believe it makes sense for Metalsmith to add some help to plugin authors for accomplishing these types of things. Basically, I am proposing a smarter files object, with methods like:

 * files.each()
 * files.filter()
 * files.sort()
 * files.groupBy()
 * files.matches()

I don't think the internal data-structure needs to change necessarilly. (although I would certainly be willing to discuss options) In order to maintain backwards compatibility, we could add this advanced data-structure to the `metalsmith` instance instead.

```js
function (_, metalsmith) {
  var files = metalsmith.files();
  // ...
}
```

Also, we could just augment the current `files` object to have these extra methods. Unfortunately, there's still the possibility of a filename clashing. (however unlikely)

I would be open to various alternatives for exactly what this collection lib should be implemented with. I'm sure there are plenty of npm modules out there.

**Comment by unstoppablecarl** [comment]
I think the files object should be left the way it is. What you are suggesting would break current compatibility as `files.each` would be a result in `Object.keys(files)`. There are packages that assist with these problems already.

https://lodash.com/
https://github.com/sindresorhus/multimatch

**Comment by ianstormtaylor** [comment]
Agree with @unstoppablecarl on this one, but not so much for backwards compatibility as for scope of the library itself. 

I definitely agree that `Object.keys` is ugly and makes it harder to read code. But I think that's more of an issue for Javascript itself that we shouldn't try to solve at the Metalsmith level. If we did, then every library that might need to benefit from looping would be responsible for paving over Javascript's problems themselves, instead of pulling that logic into `underscore` or similar.

The problem gets worse because once we allow `files.filter` and `files.matches` (or similar) because then we'll be in the business of adding more and more types of mutations directly to core that people use in plugins. The logic for "why does this mutation belong in core" will be really hard to justify over time unfortunately, leading to bloat or other frustrations.

I feel your pain though. This kind of issue is really a problem with the spec writing process and spec writing people not being in touch with those who actually use it daily. Ridiculous that we can't use `Object.values` or `Object.each` or `for (var key, value in obj)` or even nicer solutions still. Makes me long for a language that is designed with both function and taste in mind.

**Comment by dominicbarnes** [comment]
Yeah, I can see your point. I think this is something I run into often enough that I think would be useful as an npm module. (not a raw plugin, but something you `require` and pass in your local `files` object)

**Comment by ericgj** [comment]
FWIW, my plugin [metalsmith-branch](https://github.com/ericgj/metalsmith-branch) isolates the filtering logic, at least. (Needs to be brought up to the latest metalsmith deps but otherwise I think it works ok.) Haven't used it in awhile but I remember thinking I'd prefer a more controlled way of mutating the files object... often feels a little wild west-y with everything touching it asynchronously... but kind of too late to change that without breaking everything.
