### ISSUE TITLE
a little frustrated

### ISSUE THREAD

**Issue by charlespeters** [segmentio/metalsmith#122]
i've been trying to use metalsmith for a few nights now and i'm starting to get a little frustrated. i like the idea that everything is a plugin but there isn't a lot of documentation about bringing these plugins together. there a few examples but none of them really use collections or navigation permalinks to build a static site and i can't find a lot about how to setup templates. i popped into the irc chat and didn't find a lot of help, where can i go to get help to answer a few questions and get a few things clarified?

**Comment by sperand-io** [comment]
Hey charles! Want to do a screenshare?

I haven't contributed directly to the metalsmith core project, but use it / develop plugins extensively @ Segment and would be stoked to lend a hand. Then maybe you and I could figure out where exactly we're lacking in examples/docs and get that fixed.

I'm down any time this week :) let me know: chris.sperandio [at] segment [dot] com

**Comment by charlespeters** [comment]
that would be awesome that'd be awesome.

**Comment by pikeas** [comment]
@sperand-io I'm in the same boat as @charlespeters. Metalsmith seems like it hits a sweet spot of functionality, which I really appreciate, but the examples are a bit lacking (and out-of-date). I would love to see a skeleton Metalsmith/gulp setup which does all of the basics for a static site. Off the top of my head:

- Styles: {Stylus|Sass|etc} compile -> concatenate -> autoprefix -> minify -> hash -> external sourcemap
- Scripts: basically same as above.
- Base template which fills in the hashed JS/CSS bundle names.
- Smart watch for development that recompiles main styles/scripts when any included file is changed.
- Copy static assets (a bit stuck on this bit myself - trying to figure out which Gulp plugin to use so that only modified files are copied on build).
- Simple posts/blog setup, but same as static assets - only rebuild files as necessary (can be tricky if a related posts feature is present).
- Simple dev server with live reloading.
- Bonus points: style/script preprocessor linting, atom/RSS feed for blog, sitemap.

All of these bits are scattered around various articles. I have about a dozen Metalsmith-related tabs open right now, while I try to cobble this all together. This is hard - there are lots of ways to accomplish the same thing and tons of plugins to combine. It's going to be a lot of work, and I'm seriously considering switching to a static site generator I like a lot less, but which gives me more out of the box (eg, harp or docpad). I would love to see a canonical Official Implementation of a site with all the modern bells and whistles in place.

**Comment by azurelogic** [comment]
Not to self promote, but I built my site on Metalsmith recently and wrote a [blog post](https://azurelogic.com/posts/building-a-blog-with-metalsmith/) about the experience. I also gave a [more detailed talk](https://www.youtube.com/watch?v=cAq5_5Yy7Tg) this week to my local user group. I hope that helps.

**Comment by zafarali** [comment]
Hi, I really like your tutorial! Good stuff.

**Comment by ianstormtaylor** [comment]
@azurelogic very sweet! Just added those two links to the Readme too, hope that's alright.

**Comment by azurelogic** [comment]
@ianstormtaylor No complaints here. Thanks for adding it to the Readme!

@zafarali Glad you liked it. Happy to help!

**Comment by ianstormtaylor** [comment]
Totally agree, would love to have anyone who wants to commit more examples or other helpful information. Going to close this specific issue, but anyone is welcome contribute.

**Comment by jocelynlecomte** [comment]
I already wrote three posts about Metalsmith, so if you find them valuable I would be pleased to see them in the readme.
You can read them here (This is the last one, but it contains links to previous posts):
http://blog.lecomte.me/posts/2015/gentle-intro-metalsmith/build-complex-metalsmith-plugin/

I'm also planning to add more posts when I have more time.

**Comment by ianstormtaylor** [comment]
@jocelynlecomte feel free to submit a PR!
