### ISSUE TITLE
Possible to rescan directory?

### ISSUE THREAD

**Issue by twitchard** [segmentio/metalsmith#135]
Not sure if this is the right place to ask---I am writing a plugin that uses child_process to call an external utility (latexmk), which modifies the files in the src/ directory. Is it possible to have Metalsmith rescan the src/ directory, or specific file paths, so that subsequently called plugins are able to access/modify these files via the 'files' parameter? Is it possible to call Metalsmith.prototype.read() such that this happens? 
I'm sorry to ask but I can't find an example anywhere and I am not familiar enough with thunkify and generators and all the --harmony idioms to make heads or tails out of the source code.

**Comment by ianstormtaylor** [comment]
@twitchard modifying the `/src` files directly sounds like it would cause bad problems for people. Ideally it would be a utility that could act on a directory _or_ on individual file content strings, so that this wouldn't be an issue. If it has to be on a directory though, I'd recommend using `tmp` one, and then you'd need to erase all the keys in `files` and mixin the new ones again.

**Comment by MoOx** [comment]
I am working on a solid watcher that should allow that kind of modification (support partial rebuild from watched sources)
