### ISSUE TITLE
metalsmith + newer?

### ISSUE THREAD

**Issue by fantapop** [segmentio/metalsmith#144]
I'm trying to find a way to optimize our metalsmith build.   Grunt-newer looked promising but I think it works by creating a wrapper task and specifying a build with only those files that change.  Since metalsmith passes a directory in as src instead of a list of files, this doesn't work.

Do you think it would be a worthwhile change to allow a list of files to be passed in?

I realize that its possible to create metalsmith plugins that would require rebuilding all content files if one changed however thats likely an exception to the rule.

Have you thought of any other ways to optimize the metalsmith build?

**Comment by MoOx** [comment]
The (hard) problem to solve will be cache invalidation. Since all plugins might change content of a given file, on runtime, adding a such behavior might breaks lots of plugin (eg: a plugin that generate a rss with partial build might be a problem... It's just one example I am sure we can find too many of them).
For development I have worked a lot on metalsmith-watch recently to boost partial rebuild, but you have some caveats (correct for dev usage).

**Comment by fantapop** [comment]
The cache you're referring to is a previously built set of content that was generated from the rest of the files?  That's one step further than I was considering.   I was resigned to just running a build with 1 or 2 content files instead of all of them, knowing that certain outputs would be broken. For example, we generate a sitemap.xml file.  This would clearly only contain the 1 or 2 files.

metalsmith-watch looks promising. I'll definitely check it out.

**Comment by ianstormtaylor** [comment]
+1 to @MoOx here, it needs to be at the plugin level, and as something the author opts into I think, since it's impossible for a no-side-effects solution, since we can't know which files result in which output.
