### ISSUE TITLE
no longer working on node 0.12

### ISSUE THREAD

**Issue by ahmadnassri** [segmentio/metalsmith#161]
seems like you switched to io.js which is awesome, but there's no note on the website or anywhere in the docs that indicate that io should be used... when I upgraded my dependencies to latest version, it stopped working, till I realized its using generators and needed to switch to io

**Comment by Ajedi32** [comment]
You actually don't need IO.js. If you use node though it needs to be version 0.12+, and you need to run it with the --harmony_generators flag.

The `test` task in make does this automatically, which is why [the tests pass for Node 0.12](https://travis-ci.org/segmentio/metalsmith/jobs/70951934).

I agree that this should be documented somewhere.

**Comment by Ajedi32** [comment]
See also #151

**Comment by ahmadnassri** [comment]
a few points to be made here (and in relation to #151)

- usage of `--harmony` flags in node, is not a "standard" usage, so therefor, cannot expect people to understand that without proper documentation
- the reason it's not a standard, is because ES6 is not fully implemented in Node Core, and that's primarily why io.js started (and following drama)
- thankfully convergence is now here, and as you know, node.js and io.js are now one and the same team/project.
- meaning, which is the most important point here: io.js releases are considered as "next" (unstable) and node.js releases are the stable ones, therefore, metalsmith is depending on an unstable functionality / branch.

now this is not a problem for me, and many others, we can simply enable the flag, or just switch to io.js ... but as a principal, I find this flawed to release **stable** software, but depend on **unstable** platform functionality *(although very usable)*.

I certainly understand the attraction of using ES6 functionality such as generators, and I use it myself, but if I am to release a software package to the public, I would either wrap it with babel.js (or similar) and make it compatible with all the supported platform versions. this is more for the community's benefit than own preferences ... if the work is just my own, i'd be on the bleeding edge at every step of course ;)

at the end of the day, this is all nothing more than an academic discussion, the software works, and better documentation of the dependency helps.

**Comment by Ajedi32** [comment]
Yeah, I kind of agree on your point about unstable software, and I definitely agree that this should be documented somewhere.

Regarding the io.js/node convergence, I haven't been following that drama much since the split, but from what I can see now I'm not sure your assessment of io.js as being the "unstable" release of node is correct. (Or maybe I'm just misunderstanding what you were trying to say.)

Based on what I read in nodejs/node#2327, it seems like what we currently call io.js is effectively being renamed to "Node.js", and future releases of Node.js will be based on io.js. So the next major release of Node.js will be version 4.0, and it will have all the features of io.js plus a bunch of extra stuff merged over from the old Node.js repository. io.js will not be getting any new major releases.

With that in mind, I think the best course of action for Metalsmith is to simply document the flags and version requirements need for it to run on Node.js, and continue stating that it's compatible with io.js. Then when Node.js 4.0 comes out, update the documentation to state that Metalsmith is compatible with all versions of io.js, Node.js version 4.0+, and Node.js version 0.12 with the `--harmony_generators` flag set.

**Comment by ahmadnassri** [comment]
> From an outsider's perspective, this basically means Node.js's next major release will be version 4.0 and will include all the features from io.js and more, and that io.js is deprecated and will receive no new major releases.

yep, but since `4.0` is not released yet, the `io.js` branches are "unstable", by standard definition :)

> With that in mind, I think the best course of action for Metalsmith is to simply document the flags and version requirements need for it to run on Node.js, and continue stating that it's compatible with io.js. Then when Node.js 4.0 comes out, update the documentation to state that Metalsmith is compatible with all versions of io.js

yup :+1:

**Comment by woodyrew** [comment]
@ahmadnassri I think this can be closed now. Explained in the readme:  https://github.com/segmentio/metalsmith#troubleshooting

**Comment by Ajedi32** [comment]
Heh, well that was fast: https://nodejs.org/en/blog/release/v4.0.0/
