### ISSUE TITLE
metalsmith/metalsmith is dead, long live segmentio/metalsmith

### ISSUE THREAD

**Issue by woodyrew** [segmentio/metalsmith#278]
@fouad I see we've migrated back to [segmentio](https://github.com/segmentio). What is Segment's role in Metalsmith now and in the future?

**Comment by Ajedi32** [comment]
He emailed me about this last night. (Did you not receive an email too?) Key points:

* Segment is consolidating all their open source projects under the segmentio org
* The metalsmith.io website and other related projects are staying under the Metalsmith org for now "so that the plugin ecosystem isn't limited to segmentio namespace"
* Segment is currently looking internally for developers who might be interested in taking on a more active role in maintaining metalsmith

Other than that, nothing's really changing as far as I can tell. I'm sure @fouad will be happy to answer any other questions you might have.

**Comment by woodyrew** [comment]
No email apart from the segmentio/metalsmith invitation. Thanks for passing on the information.

Some help from Segment in maintaining, etc, would be good. I've recently moved and started a new job so I've not had much time of late.

**Comment by fouad** [comment]
thanks for jumping in @Ajedi32!

Hi @woodyrew! I just realized I messed up and sent the email to your a `users.noreply.github` email (wasn't paying attention when I copy-pasted). Andrew brought up all the main points & I'm happy to answer any other q's you have! (emailing fouad@segment.com will prob get a faster response too)

**Comment by axe312ger** [comment]
@Ajedi32 any updates there internally?

Especially some of the plugins maintained by segmentio could really use some love. So many open PR's :(

**Comment by woodyrew** [comment]
@axe312ger Ajedi32's not employed by Segment.

> ... any updates there internally?
>
> Especially some of the plugins maintained by segmentio could really use some love. So many open PR's :(

@fouad Are you able to field this one?

**Comment by axe312ger** [comment]
Personally I would love to see all of these unmaintained moduels moved to the metalsmith org and some people more given access to merge PR's.

The community can do the rest, the biggest problem Metalsmith IMHO has, is unmaintained plugins while community is still heavily using and developing for them

**Comment by ismay** [comment]
@f2prateek I have a question about the move, thought I'd message you instead of fouad since he now works for usermirror. Do you know what motivated the move of metalsmith core and some of the plugins to segmentio?

> Segment is consolidating all their open source projects under the segmentio org

I'm asking because I personally think it makes sense to have the core metalsmith library (and highly used plugins) under the metalsmith org. That's the first place where I'd look for it as a user.

It's also the reason I recently moved metalsmith-layouts and metalsmith-in-place to the metalsmith org. We've had questions in the past about whether metalsmith is dead, etc., and I think having a lively organisation that owns the important parts of metalsmith and is able to move quick is a big part of gaining a user's trust.

If we know of the reasons that motivated the move, maybe we could address them? Satisfy both segment's and the metalsmith project's needs? I'm just speaking for myself, and maybe I'm overestimating the importance of the org owning the main parts of metalsmith, but I think it would be a healthy move and I don't see how it would be detrimental to segment.
