### ISSUE TITLE
is metalsmith maintained?

### ISSUE THREAD

**Issue by el-j** [segmentio/metalsmith#329]
when i run an upgrade to upgrade the packages from my metalsmith project i got at least this warnings. is there any maintaining of metalsmith or should i move on to a newer/other static generator? (gatsby e.g.)
```
warning metalsmith > gray-matter > coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
warning metalsmith-assets > recursive-readdir > minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

thank you

**Comment by leviwheatcroft** [comment]
This question get's asked a lot.

Basically `metalsmith` (the core package) is rock solid, there's been no new versions in the last 3 years because the core functionality works well and the plugin ecosystem provides the rest.

Conversely, the plugin ecosystem is vast, and while the common ones are well maintained and robust, many of the more obscure plugins are poorly maintained.

Your first warning concerns the metalsmith core, and I guess you should post an issue asking to bump the gray-matter version to kill this warning, but to me it doesn't seem very critical.

The second warning is from that plugin `metalsmith-assets`, which seems to be [deprecated](https://github.com/treygriffith/metalsmith-assets), likely because it doesn't actually do anything. You don't need to do anything special to include static assets in your build, you just put them in your source directory and metalsmith will move them across.
