### ISSUE TITLE
Make boilerplate documentation with stubs

### ISSUE THREAD

**Issue by coolshaurya** [segmentio/metalsmith#331]
According to me -
We should design some official place (preferably a new docs repo) for formal documentation and link this to the README and the site. This may not necessarily replace the info on the homepage. We should also create a structure and some boilerplate markdown files with headings. All of these will initially be stubs and can later be filled in by the community and the maintainers/project owners. This will help us get started on the documentation which is a major barrier in metalsmith's popularity. (see issue #219 )

An example topic structure -

- What is Metalsmith
- Philosophy
- Getting Started
  * Installation
  * Usage
  * An Example Site using Metalsmith
- Examples
  * all the examples on the site
- Plugins for common tasks
- API specification
- Misc

**Comment by coolshaurya** [comment]
I am willing to contribute the stubs for this if someone makes a repo.

**Comment by ismay** [comment]
@coolshaurya Thanks for the suggestion. We've tried multiple approaches to documentation and examples in the past. We've had a separate repo with examples. However, that got out of date pretty quickly.

What I'm doing with in-place (https://github.com/metalsmith/metalsmith-in-place/wiki) and layouts (https://github.com/metalsmith/metalsmith-layouts/wiki) is to keep the docs and examples close to the plugin itself. Since the ecosystem for metalsmith plugins isn't centralised I think that that works best. You can check out the wiki's for both repos to see the examples, and the READMEs for the general docs.

In addition to that I think that more centralised documentation for metalsmith as a whole should be part of metalsmith.io. The site has been rebuilt technically a while back, but there are still a bunch of issues that need to be addressed before we'd tackle that (like splitting up the page into multiple smaller pages).

After metalsmith.io has been cleaned up, I think that that would be the perfect place for some decent docs and examples. For the examples I'd ideally prefer some live playground examples, so it's easy for people to see it in action and tinker with it (I'm not sure what service would fit best there).

So if you're willing to contribute I think https://github.com/metalsmith/metalsmith.io would be a good start. But help is appreciated in other areas as well. I'll close this as I hope this answers your question, but feel free to comment if you want to know more!
