### ISSUE TITLE
Maintainer/ Contributor application

### ISSUE THREAD

**Issue by webketje** [segmentio/metalsmith#335]
Dear metalsmith maintainers,

The Slack app is in maintenance, and I see no point of contact or platform to get in touch with you or offer help, so I will use this issue to do so. Metalsmith is still very popular on NPM and rightfully so, because it's got the philosophy _**just right**_ for its usecase, but issues & PR's remain open for years and I think you could use a helping hand.

I would love to help get metalsmith back on track and take it _further_ (without touching its core principles).
In fact I already [resolved conflicts for an old PR](https://github.com/metalsmith/metalsmith.io/pull/301), contributed to [metalsmith-filemetadata](https://github.com/dpobel/metalsmith-filemetadata/commits/master) and released 2 own plugins ([metalsmith-taxonomy](https://www.npmjs.com/package/metalsmith-taxonomy) & [metalsmith-handlebars-x](https://www.npmjs.com/package/metalsmith-handlebars-x)) (hope that testifies as a proof of my involvement).

In concreto, I would like to contribute:
- Reviewing existing issues & testing & validating PR's
- Helping with splitting the website into multiple pages
- Adding documentation/ example/ tutorial proposals
- Investigate using the Github or NPM API (searching for keywords) to replace the PR-based 'static' plugin list.

I have extensive knowledge of:
- the metalsmith ecosystem
- Javascript & NodeJS
- Git releases & NPM publishing
- Linux/ Windows OS

Please let me know how I can get in touch and eventually help & become part of the team.

**Comment by Ajedi32** [comment]
Sounds like you're primarily interested in maintaining the metalsmith.io site? I'd be fine with that. The project could certainly use some more energetic collaborators. Anyone else have any thoughts on this? @woodyrew @ismay

**Comment by ismay** [comment]
> Sounds like you're primarily interested in maintaining the metalsmith.io site? I'd be fine with that. The project could certainly use some more energetic collaborators. Anyone else have any thoughts on this? @woodyrew @ismay

Personally I'm fine with it. And to explain why I haven't been active with the project, I disagree with Segment's role in it. They're keeping certain administrative roles/permissions from us, and won't move metalsmith codebases from their org to the metalsmith organisation. That hamstrings the entire project and keeps us from effectively maintaining it. I've asked them multiple times to resolve it, but nothing has happened. That's why I've barely contributed lately, if at all.

**Comment by woodyrew** [comment]
I'm happy with @webketje to be added to help maintaining metalsmith.io.

On the point @ismay makes, I'd be happy to fork the project under another name and for the community to have full control. Segment don't provide any support for the project so there's little incentive to stay under their umbrella.

**Comment by ismay** [comment]
> On the point @ismay makes, I'd be happy to fork the project under another name and for the community to have full control. Segment don't provide any support for the project so there's little incentive to stay under their umbrella.

I agree. I think that'd probably be best for the project. I'm not sure how much time I'll be able to devote to it, as I'm already juggling two careers, but at least it'll ensure we have full rights over the project and allow us to maintain it.

**Comment by webketje** [comment]
Thank you for the positive feedback,

@Ajedi32 I'm _not necessarily primarily_ interested in updating the website, but as has been previously said somewhere: metalsmith's core is rock-solid, and I think the website is currently the area where most improvement can be done,
but I'm just as interested in reviewing PR's on the main repo, and core plugins (metalsmith-layouts/ permalinks, ...).

So I was applying to be a *member of the metalsmith org*, but I fully understand and would be more than happy to be invited as contributor to 1 repo as *trial membership* .

For all open PR's/issues I would first pull locally, test, and either reject, validate, or improve the PR in a feature/bugfix branch & ask for approval by at least one of you. I'll be happy to hear additional rules to adhere to in a ... perhaps more conversational channel?

I think there is merit in having a Gitter chat for this and more : https://gitter.im (only the members of the metalsmith Github org can set this up).

I noticed the issue with segment.io's ownership in previous Github issues, and also think metalsmith/metalsmith would make more sense. 

Going forward (prematurely), I "secured" the NPM org @metalsmith in case an org migration would happen (e.g. @metalsmith/permalinks instead of metalsmith-permalinks). I'll be happy to add you or transfer it to one of you.

**Comment by webketje** [comment]
Still haven't gotten an update/ invitation concerning this issue, please follow up @ismay @woodyrew @Ajedi32 .
Thank you

**Comment by webketje** [comment]
Still haven't gotten an update/ invitation concerning this issue, please follow up @ismay @woodyrew @Ajedi32.
Sorry for the nags, I want to move this project forward.
Thank you

**Comment by Ajedi32** [comment]
@webketje Sorry for the delay in responding. Since there seem to be no objections, I've added you as a collaborator on the Metalsmith.io repository. Feel free to start making improvements as you see fit.

I don't have the ability to grant membership for the Metalsmith org, but I believe that if that's something other members would be okay with then @woodyrew has the necessary permissions.

As for the Metalsmith core repo (and other popular plugins hosted under the segmentio org), that's controlled by Segment and I don't believe anyone in this thread has the ability to grant write access to that.

If you find yourself wanting to contribute to core it might actually be worth it to just fork the project and start making changes. As long as you don't break backwards compatibility all existing Metalsmith plugins would work just fine with your fork, and core currently has a rather low commit velocity so upstreaming your changes later most likely wouldn't be too difficult.

**Comment by webketje** [comment]
@woodyrew could you add me to the metalsmith org? I'd like to create a fork of segmentio/metalsmith there, setup a Gitter chat, and replace the website banner for slack with that.
