### ISSUE TITLE
Enable/disable plugins via the CLI

### ISSUE THREAD

**Issue by RobLoach** [segmentio/metalsmith#98]
Allow enabling/disabling plugins through the CLI application. If you have a set of plugins in `metalsmith.json`, allow disabling a select few for certain situations.

**Comment by tmcw** [comment]
:+1: it's very useful to have metalsmith-watch locally & for development, but as an npm script pre-publish, it isn't

**Comment by ianstormtaylor** [comment]
Curious to see what an idea for the API would look like.

Might be a reason to include the watching functionality at the core CLI level, instead of in a plugin. I think (can't remember) the watch plugin only re-runs on individual files, which is leaky anyways.

**Comment by RobLoach** [comment]
I've been pushing any development functionality (like watch) over to Grunt/Gulp, and then triggering Metalsmith through [grunt-exec](https://www.npmjs.com/package/grunt-exec)/[gulp-exec](https://github.com/robrich/gulp-exec). This leaves Metalsmith strictly responsible for building, while Gulp/Grunt only assist with development. Metalsmith core itself should be kept as lean as possible.

If there was a `--disable-plugin` argument, then `metalsmith.json` could house the configuration for `metalsmith-watch`, and disable it in production environments.

**Comment by ianstormtaylor** [comment]
I think I'm just not convinced that keeping all of the config in a single JSON and then cherrypicking is the cleanest way to go, since it leads to confusion. Seems like it would be easier if it was either just written in Javascript, which is easy to do. Or it could be two config files, which is more standard, although adds duplication.

**Comment by RobLoach** [comment]
> Or it could be two config files, which is more standard, although adds duplication.

Interesting idea... Perhaps inherited configurations? `metalsmith-prod.json` would override defaults from `metalsmith.json`? Is this getting a bit too complicated? :thought_balloon:

**Comment by ianstormtaylor** [comment]
It seems kind of reasonable, but I think for simplicity's sake at that point it's probably better to just run the thing with the Javascript API where you have complete control? Since ideally lots of the config would be shared with not just Metalsmith in the case of slightly more complex setups (eg. shared with other build systems).

**Comment by ianstormtaylor** [comment]
Closing in favor of the differing configs, or the regular Javascript route.
